export { Landing } from './landing/index.jsx'
export { BgFade } from './bg-fade/index.jsx'
export { Navbar } from './navbar/index.jsx'
export { Profile } from './profile/index.jsx'
export { AboutMe } from './about-me/index.jsx'
