export { Landing } from './landing/index.jsx'
export { BgFade } from './bg-fade/index.jsx'
export { BgStatic } from './bg-static/index.jsx'
export { NavbarFadeIn } from './navbar-fade-in/index.jsx'
export { NavbarStatic } from './navbar-static/index.jsx'
export { Profile } from './profile/index.jsx'
export { Projects } from './projects/index.jsx'
export { AboutMe } from './about-me/index.jsx'
export { Contact } from './contact/index.jsx'

export { DelayLink } from './delay-link/index.jsx'
